# Generated by Django 4.1.7 on 2023-04-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_followingorganization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="date_of_birth",
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
