# Generated by Django 4.1.7 on 2023-03-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
