version: "3.3"

services:
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - afisha_net
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redisdata:/var/lib/redis/data
    networks:
      - afisha_net
  api:
    tty: true
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/afisha
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - afisha_net
    depends_on:
      - postgres
volumes:
  pgdata:
  redisdata:
networks:
  afisha_net: {}
